apiVersion: v1
kind: Pod
metadata:
  name: db2
  labels:
    app: db2
spec:
  volumes:
  - name: pv2
    persistentVolumeClaim:
      claimName: pvc2
  containers:
  - image: mongo
    name: container2
    command:
    - mongod
    - "--bind_ip"
    - "0.0.0.0"
    ports:
    - containerPort: 27017
    volumeMounts:
    - name: pv2
      mountPath: /data/db
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: db2
  name: db2-service
spec:
  ports:
    - port: 27017
      targetPort: 27017
      protocol: TCP
  selector:
    app: db2
        