apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv2
spec:
 accessModes:
 - ReadWriteMany
 capacity:
   storage: 1Gi
 hostPath:
   path: /tmp/pv2
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc2
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: ""