apiVersion: v1
kind: Pod
metadata:
  name: db1
  labels:
    app: db1
spec:
  volumes:
  - name: pv1
    persistentVolumeClaim:
      claimName: pvc1
  containers:
  - image: mongo
    name: container1
    command:
    - mongod
    - "--bind_ip"
    - "0.0.0.0"
    ports:
    - containerPort: 27017
    volumeMounts:
    - name: pv1
      mountPath: /data/db