apiVersion: v1
kind: Pod
metadata:
  name: db4
  labels:
    app: db4
spec:
  volumes:
  - name: pv4
    persistentVolumeClaim:
      claimName: pvc4
  containers:
  - image: mongo
    name: container4
    command:
    - mongod
    - "--bind_ip"
    - "0.0.0.0"
    ports:
    - containerPort: 27017
    volumeMounts:
    - name: pv4
      mountPath: /data/db