apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: finosys-fe
  name: finosys-fe
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: finosys-fe
  type: LoadBalancer
status:
  loadBalancer: {}
