apiVersion: apps/v1
kind: Deployment
metadata:
  name: finosys-be1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: be1
  template:
    metadata:
      labels:
        app: be1
    spec:
      containers:
      - image: fazzyaziz/finosys-be1:v1
        name: container-be1
        imagePullPolicy: "Always"
        ports:
        - containerPort: 5000
        envFrom:
        - configMapRef:
            name: be1-config